#pragma once

#include "core/World.hpp"
#include "core/GameLoop.hpp"
#include "core/SceneSerializer.hpp"
#include "core/definitions.hpp"
#include "core/GameLoop.hpp"
#include "core/Time.hpp"
#include "core/SceneSerializer.hpp"
#include "core/WorldContext.hpp"
#include "core/WorldManager.hpp"
#include "core/ServiceContext.hpp"


#include "components/Hierarchy.hpp"
#include "components/NameComponent.hpp"
#include "components/Transform.hpp"
#include "components/Sprite.hpp"
#include "components/Trail.hpp"
#include "components/SpriteAnimation.hpp"
#include "components/CameraComponent.hpp"
#include "components/PostProcessing.hpp"
#include "components/NullComponent.hpp"
#include "components/RigidBody2D.hpp"
#include "components/CollisionSensor.hpp"
#include "components/TilemapComponent.hpp"
#include "components/ParticleEmisor.hpp"
#include "components/LightSource.hpp"
#include "components/AudioSource.hpp"
#include "components/MovementVector.hpp"
#include "components/ProceduralTexture.hpp"
#include "components/PrefabComponent.hpp"



#include "systems/Physics.hpp"
#include "systems/DebugPhysics.hpp"
#include "systems/RenderClear.hpp"
#include "systems/RenderSprite.hpp"
#include "systems/RenderAnimation.hpp"
#include "systems/TrailSystem.hpp"
#include "systems/CameraSystem.hpp"
#include "systems/RenderDisplay.hpp"
#include "systems/TilemapSystem.hpp"
#include "systems/ParticleSystem.hpp"
#include "systems/Light2DSystem.hpp"
#include "systems/DebugGUI.hpp"
#include "systems/AudioSystem.hpp"
#include "systems/PostProcessingSystem.hpp"
#include "systems/VolumetricPostProcessingSystem.hpp"
#include "systems/ProceduralTextureSystem.hpp"
#include "systems/NavmeshSystem.hpp"
#include "systems/PrefabSystem.hpp"
#include "systems/SaveEntityMapSystem.hpp"


#include "services/ImageLoader.hpp"
#include "services/EventService.hpp"
#include "services/Config.hpp"
#include "services/RenderContext.hpp"
#include "services/WorldManagerDS.hpp"
#include "services/AnimationDefinitionService.hpp"
#include "services/ShaderLoader.hpp"
#include "services/Renderer2D.hpp"
#include "services/AudioService.hpp"
#include "services/ImguiService.hpp"
#include "services/EditorDS.hpp"


#include "commonStructures/Camera.hpp"
#include "commonStructures/AnimationDefinition.hpp"
#include "commonStructures/Navmesh.hpp"

#include "opengl/BatchRenderer.hpp"
#include "opengl/Framebuffer.hpp"
#include "opengl/Shader.hpp"
#include "opengl/Texture.hpp"

#include "ComponentVariant.hpp"
